package com.tan.gratify.ui.screen.playlist

import com.tan.domain.data.model.searchResult.songs.Artist
import com.tan.domain.data.model.searchResult.songs.Thumbnail
import androidx.compose.runtime.*
import androidx.compose.material3.*
import com.tan.gratify.ui.component.*
import com.tan.domain.utils.toSongEntity
import com.tan.gratify.viewModel.UIEvent
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.material.icons.rounded.*
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import gratify.composeapp.generated.resources.*
import org.jetbrains.compose.resources.stringResource
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.TimeoutCancellationException
import kotlinx.coroutines.withTimeout

import com.tan.gratify.ui.theme.GratifyColors

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.material.icons.Icons
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.unit.dp
import androidx.navigation.NavController
import coil3.compose.AsyncImage
import coil3.compose.LocalPlatformContext
import coil3.request.ImageRequest
import com.kmpalette.rememberPaletteState
import com.tan.common.Config
import com.tan.domain.data.entities.SharedPlaylist
import com.tan.domain.data.entities.SharedPlaylistTrack
import com.tan.domain.data.model.browse.album.Track
import com.tan.domain.data.model.social.CloudPlaylistDto
import com.tan.domain.data.model.social.CloudPlaylistItemDto
import com.tan.domain.mediaservice.handler.PlaylistType
import com.tan.domain.mediaservice.handler.QueueData
import com.tan.domain.repository.LocalPlaylistRepository
import com.tan.domain.repository.SharedPlaylistRepository
import com.tan.domain.repository.SocialRepository
import com.tan.gratify.expect.ui.toImageBitmap
import com.tan.gratify.extension.getColorFromPalette
import com.tan.gratify.ui.theme.typo
import com.tan.gratify.viewModel.SharedViewModel
import io.github.jan.supabase.auth.auth
import io.github.jan.supabase.postgrest.postgrest
import kotlinx.coroutines.flow.collect
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.firstOrNull
import kotlinx.coroutines.launch
import org.koin.compose.koinInject

fun SharedPlaylistTrack.toTrack(): Track {
    return Track(
        album = null,
        artists = listOf(Artist(name = this.artists, id = null)),
        duration = this.durationSeconds?.let { "${it / 60}:${(it % 60).toString().padStart(2, '0')}" },
        durationSeconds = this.durationSeconds,
        isAvailable = true,
        isExplicit = false,
        likeStatus = null,
        thumbnails = listOf(Thumbnail(url = "https://i.ytimg.com/vi/${this.videoId}/mqdefault.jpg", width = 320, height = 180)),
        title = this.title,
        videoId = this.videoId,
        videoType = "MUSIC_VIDEO_TYPE_ATV",
        category = null,
        feedbackTokens = null,
        resultType = "song",
        year = null
    )
}

@Composable
fun SharedPlaylistScreen(
    playlistId: String,
    navController: NavController,
    sharedViewModel: SharedViewModel = koinInject(),
    sharedPlaylistRepository: SharedPlaylistRepository = koinInject(),
    socialRepository: SocialRepository = koinInject(),
    localPlaylistRepository: LocalPlaylistRepository = koinInject(),
    supabase: io.github.jan.supabase.SupabaseClient = koinInject(),
) {
    val scope = rememberCoroutineScope()
    var playlist by remember(playlistId) { mutableStateOf<SharedPlaylist?>(null) }
    var tracks by remember(playlistId) { mutableStateOf<List<SharedPlaylistTrack>>(emptyList()) }
    var isLoading by remember(playlistId) { mutableStateOf(true) }
    var retry by remember(playlistId) { mutableStateOf(0) }
    var isSaved by remember(playlistId) { mutableStateOf(false) }
    var isSaving by remember(playlistId) { mutableStateOf(false) }
    var showDeleteDialog by remember(playlistId) { mutableStateOf(false) }
    var isDeleting by remember(playlistId) { mutableStateOf(false) }
    var chosenTrack by remember(playlistId) { mutableStateOf<Track?>(null) }
    val currentUserId = supabase.auth.currentUserOrNull()?.id
    val controller by sharedViewModel.controllerState.collectAsStateWithLifecycle()
    val queueData by sharedViewModel.getQueueDataState().collectAsStateWithLifecycle()
    val nowPlaying by sharedViewModel.nowPlayingState.collectAsStateWithLifecycle()
    val queueId = "SHARED_$playlistId"
    val domainTracks = remember(tracks) { tracks.map { it.toTrack() } }
    val paletteState = rememberPaletteState()
    var bitmap by remember(playlistId) { mutableStateOf<ImageBitmap?>(null) }
    var paletteGenerated by remember(playlistId) { mutableStateOf(false) }
    LaunchedEffect(bitmap) {
        if (bitmap != null && !paletteGenerated) {
            paletteState.generate(bitmap!!)
            paletteGenerated = true
        }
    }

    LaunchedEffect(playlistId, retry) {
        isLoading = true
        playlist = null
        tracks = emptyList()
        try {
            withTimeout(20_000) {
                val result = sharedPlaylistRepository.getSharedPlaylist(playlistId)
                val trackResult = sharedPlaylistRepository.getSharedPlaylistTracks(playlistId).first()
                if (result.getOrNull() != null && trackResult.isSuccess) {
                    playlist = result.getOrNull()
                    tracks = trackResult.getOrThrow()
                } else {
                    val dto = supabase.postgrest["cloud_playlists"].select {
                        filter { eq("id", playlistId) }
                    }.decodeList<CloudPlaylistDto>().firstOrNull()
                    if (dto != null) {
                        val items = socialRepository.getCloudPlaylistItems(playlistId).first().getOrThrow()
                        tracks = items.mapIndexed { index, item ->
                            SharedPlaylistTrack(id = item.id ?: "${playlistId}_$index", playlistId = playlistId,
                                videoId = item.videoId, title = item.title, artists = item.artist,
                                durationSeconds = item.duration, createdAt = null)
                        }
                        playlist = SharedPlaylist(id = dto.id ?: playlistId, userId = dto.userId ?: "",
                            title = dto.title, thumbnailUrl = dto.thumbnailUrl, creatorName = null, createdAt = null)
                    }
                }
                isSaved = localPlaylistRepository.getLocalPlaylistBySourceSharedId(playlistId) != null
            }
        } catch (_: TimeoutCancellationException) {
            playlist = null
        } catch (error: CancellationException) {
            throw error
        } catch (_: Exception) {
            playlist = null
        } finally {
            isLoading = false
        }
    }
    if (isLoading) {
        CollectionDetailLoading(onBack = { navController.navigateUp() })
        return
    }
    val data = playlist
    if (data == null) {
        CollectionDetailError(onBack = { navController.navigateUp() }, onRetry = { retry++ })
        return
    }
    val playTrack: (Track, List<Track>) -> Unit = { first, queue ->
        sharedViewModel.setQueueData(QueueData.Data(listTracks = queue.toCollection(ArrayList()), firstPlayedTrack = first,
            playlistId = queueId, playlistName = data.title, playlistType = PlaylistType.PLAYLIST, continuation = null))
        sharedViewModel.loadMediaItemFromTrack(first, type = Config.SONG_CLICK)
    }
    val onSave: () -> Unit = {
        if (!isSaving) {
            isSaving = true
            scope.launch {
                try {
                    if (!isSaved) {
                        localPlaylistRepository.saveSharedPlaylistToLibrary(sharedPlaylistId = playlistId, title = data.title,
                            thumbnail = data.thumbnailUrl, tracks = domainTracks, creatorName = data.creatorName)
                        currentUserId?.let { sharedPlaylistRepository.recordPlaylistSave(playlistId, it).getOrThrow() }
                        isSaved = true
                        playlist = data.copy(addCount = data.addCount + 1)
                    } else {
                        currentUserId?.let { sharedPlaylistRepository.removePlaylistSave(playlistId, it).getOrThrow() }
                        localPlaylistRepository.getLocalPlaylistBySourceSharedId(playlistId)?.let {
                            localPlaylistRepository.deleteLocalPlaylist(it.id, "Removed").collect {}
                        }
                        isSaved = false
                        playlist = data.copy(addCount = (data.addCount - 1).coerceAtLeast(0))
                    }
                } catch (error: CancellationException) {
                    throw error
                } catch (_: Exception) {
                    isSaved = localPlaylistRepository.getLocalPlaylistBySourceSharedId(playlistId) != null
                    sharedViewModel.makeToast("Gagal memperbarui koleksi. Coba lagi.")
                } finally { isSaving = false }
            }
        }
    }
    val lazyState = rememberLazyListState()
    val collapsed by remember { derivedStateOf { lazyState.firstVisibleItemIndex > 0 } }
    Box(Modifier.fillMaxSize().background(GratifyColors.Background)) {
        LazyColumn(Modifier.fillMaxSize(), state = lazyState, contentPadding = PaddingValues(bottom = 120.dp)) {
            item(key = "collection-header", contentType = "header") {
                CollectionDetailHeader(title = data.title, kind = stringResource(Res.string.playlist),
                    subtitle = data.creatorName.orEmpty(),
                    metadata = stringResource(Res.string.album_length, tracks.size.toString(), "") + if (data.addCount > 0) " • ${data.addCount} " + stringResource(Res.string.detail_saves) else "",
                    accent = paletteState.palette?.getColorFromPalette() ?: playlistTitleGradient(data.title).first(),
                    onBack = { navController.navigateUp() }, isPlaying = controller.isPlaying && queueData?.data?.playlistId == queueId,
                    canPlay = domainTracks.isNotEmpty(),
                    onPlay = {
                        if (queueData?.data?.playlistId == queueId) sharedViewModel.onUIEvent(UIEvent.PlayPause)
                        else domainTracks.firstOrNull()?.let { playTrack(it, domainTracks) }
                    },
                    onShuffle = { domainTracks.shuffled().let { queue -> queue.firstOrNull()?.let { playTrack(it, queue) } } },
                    artwork = { modifier ->
                        if (isAutoAssignedOrNullThumbnail(data.thumbnailUrl) && tracks.isNotEmpty()) {
                            PlaylistCollageThumbnail(tracks = tracks.take(4).map { it.videoId }, placeholderTitle = data.title,
                                onSuccessFirstCell = { bitmap = it.image.toImageBitmap() }, modifier = modifier)
                        } else AsyncImage(model = ImageRequest.Builder(LocalPlatformContext.current).data(data.thumbnailUrl).size(512, 512).build(),
                            placeholder = painterPlaylistThumbnail(data.title, style = typo().labelMedium, 250.dp to 250.dp),
                            error = painterPlaylistThumbnail(data.title, style = typo().labelMedium, 250.dp to 250.dp),
                            contentDescription = data.title, contentScale = ContentScale.Fit,
                            onSuccess = { bitmap = it.result.image.toImageBitmap() }, modifier = modifier)
                    },
                    actions = {
                        if (data.userId != currentUserId) CollectionSaveAction(isSaved, enabled = !isSaving && tracks.isNotEmpty(), onClick = onSave)
                        else CollectionDetailAction(Icons.Rounded.DeleteOutline, stringResource(Res.string.delete_playlist), enabled = !isDeleting, onClick = { showDeleteDialog = true })
                    },
                )
            }
            if (tracks.isEmpty()) item { CollectionDetailEmpty() }
            itemsIndexed(domainTracks, key = { index, track -> "${track.videoId}_$index" }, contentType = { _, _ -> "song" }) { _, track ->
                SongFullWidthItems(collectionStyle = true, track = track, isPlaying = controller.isPlaying && nowPlaying?.songEntity?.videoId == track.videoId,
                    onClickListener = { playTrack(track, domainTracks) }, onMoreClickListener = { chosenTrack = track },
                    onAddToQueue = { sharedViewModel.addListToQueue(arrayListOf(track)) }, modifier = Modifier.fillMaxWidth())
            }
        }
        androidx.compose.animation.AnimatedVisibility(collapsed, enter = androidx.compose.animation.fadeIn(), exit = androidx.compose.animation.fadeOut()) {
            CollectionDetailTopBar(data.title, onBack = { navController.navigateUp() })
        }
    }
    chosenTrack?.let { track ->
        NowPlayingBottomSheet(onDismiss = { chosenTrack = null }, navController = navController, song = track.toSongEntity())
    }
    if (showDeleteDialog) AlertDialog(onDismissRequest = { if (!isDeleting) showDeleteDialog = false },
        title = { Text(stringResource(Res.string.delete_playlist)) }, text = { Text(data.title) },
        confirmButton = {
            TextButton(enabled = !isDeleting, onClick = {
                isDeleting = true
                scope.launch {
                    try {
                        sharedPlaylistRepository.deleteSharedPlaylist(playlistId).getOrThrow()
                        navController.navigateUp()
                    } catch (error: CancellationException) { throw error }
                    catch (_: Exception) { sharedViewModel.makeToast("Gagal menghapus playlist. Coba lagi.") }
                    finally { isDeleting = false; showDeleteDialog = false }
                }
            }) { Text(stringResource(Res.string.delete_playlist)) }
        }, dismissButton = { TextButton(enabled = !isDeleting, onClick = { showDeleteDialog = false }) { Text(stringResource(Res.string.cancel)) } })
}
